import { StyleSheet } from 'react-native';
export const colors = {
  bg: '#090C0B',
  panel: '#141A17',
  raised: '#1D2721',
  border: '#33443A',
  text: '#F1F5F2',
  muted: '#ACBDB1',
  green: '#65E497',
  error: '#FFB4AB',
};
export const ui = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.bg },
  body: { padding: 20, gap: 16 },
  title: { color: colors.text, fontSize: 26, fontWeight: '700' },
  text: { color: colors.text, fontSize: 16, lineHeight: 24 },
  muted: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  error: { color: colors.error, fontSize: 16, lineHeight: 24 },
  panel: {
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 16,
    gap: 12,
  },
  input: {
    color: colors.text,
    backgroundColor: colors.panel,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    minHeight: 48,
    fontSize: 16,
  },
  button: {
    minHeight: 48,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.raised,
  },
  primary: { backgroundColor: colors.green },
  buttonText: { color: colors.text, fontSize: 16, fontWeight: '600' },
  primaryText: { color: colors.bg, fontSize: 16, fontWeight: '700' },
  row: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
});
